[package]
authors = ["Brad Gibson"]
name = "quickstart_template"
version = "0.1.0"

[[bin]]
doc = false
name = "quickstart_template"
path = "src/bin/quickstart_template/bin.rs"
test = false

[dependencies]
assayer = "0.2.2"
libc = "0.2.31"

[dependencies.derive-fail]
git = "https://github.com/withoutboats/derive-fail"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"

[lib]
name = "quickstart_template"
path = "src/lib/quickstart_template.rs"
