[package]
authors = ["Brad Gibson"]
name = "quickstart_template"
version = "0.1.0"

[[bin]]
doc = false
name = "quickstart_template"
path = "src/bin/main.rs"
test = false
[dependencies.clippy]
optional = true
version = "*"

[dependencies.failure]
version = "0.*"

[dependencies.failure_derive]
version = "0.*"

[dependencies.galvanic-assert]
version = "*"

[dependencies.galvanic-mock]
features = ["galvanic_assert_integration"]
version = "*"

[dependencies.galvanic-test]
features = ["galvanic_mock_integration"]
version = "*"

[dependencies.libc]
version = "~0"

[features]
default = ["clippy"]

[lib]
name = "quickstart_template"
path = "src/lib/quickstart_template.rs"
[profile.bench]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "unwind"
rpath = false

[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.doc]
codegen-units = 1
debug = 2
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "unwind"
rpath = false

[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[workspace]
