[package]
authors = ["Brad Gibson"]
name = "quickstart_template"
version = "0.1.0"

[[bin]]
doc = false
name = "quickstart_template"
path = "src/bin/main.rs"
test = false

[dependencies]
galvanic-assert = "0.8.6"
galvanic-mock = "0.1.2"
galvanic-test = "0.1.3"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"

[dependencies.failure_derive]
git = "https://github.com/withoutboats/failure_derive"

[dependencies.libc]
version = "~0"

[dev-dependencies]
galvanic-assert = "*"

[dev-dependencies.galvanic-mock]
features = ["galvanic_assert_integration"]
version = "*"

[dev-dependencies.galvanic-test]
features = ["galvanic_mock_integration"]
version = "*"

[features]
default = ["clippy"]

[lib]
name = "quickstart_template"
path = "src/lib/quickstart_template.rs"
[profile.bench]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "unwind"
rpath = false

[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.doc]
codegen-units = 1
debug = 2
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "unwind"
rpath = false

[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[workspace]
