[package]
authors = ["Brad Gibson"]
name = "quickstart_template"
version = "0.4.0"

[lib]
name = "quickstart_template"
path = "src/lib/quickstart_template.rs"

[[bin]]
doc = false
name = "quickstart_template"
path = "src/bin/main.rs"
test = false

[dependencies]
libc = "0.2.31"
clippy = {version = "*", optional = true}

[dependencies.assayer]
git = "https://github.com/humanenginuity/assayer"

[dependencies.derive-fail]
git = "https://github.com/withoutboats/derive-fail"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"

[features]
default = []
