[package]
authors = ["Brad Gibson"]
name = "quickstart_template"
version = "0.4.0"

[[bin]]
doc = false
name = "quickstart_template"
path = "src/app/main.rs"
test = false

[dependencies]
libc = "0.2.31"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.derive-fail]
git = "https://github.com/withoutboats/derive-fail"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"

[features]
default = []

[lib]
name = "quickstart_template"
path = "src/lib/quickstart_template.rs"
